config/routes.rb
Rails.application.routes.draw do
  root to: "users#activity"
  get 'test/new'

  resources :group_users
  patch "/editable", to: "editables#update"
  get "/backend", to: "backend#show", as: 'backend'

  resources :groups
  
  get "/categories/manage", to: "categories#manage", as: 'manage_categories'
  resources :categories, shallow: true do
    get "sub_categories/new", to: "categories#new", as: 'new_sub_category'
    resources :topics, shallow: true do
      resources :posts, shallow: true do
        resources :attachments
      end
    end
  end

  resources :users, shallow: true do
    resources :user_roles
    resources :user_groups
    resources :media
  end
  resources :roles, shallow: true do
    resources :role_permissions
  end
  resources :permissions
    
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :setting_groups, shallow: true do
    resources :settings, shallow: true
  end
  get "/settings", to: "settings#index"
end

app/models/setting_group.rb
class SettingGroup < ActiveRecord::Base
  belongs_to :setting_group 
  has_many :setting_groups
  has_many :settings
  
  scope :root, ->{ where(setting_group_id: nil) }
end

app/controllers/setting_groups_controller.rb
class SettingGroupsController < ApplicationController
  before_action :set_setting_group, only: [:show, :edit, :update, :destroy]
  layout "backend"

  # GET /setting_groups
  # GET /setting_groups.json
  def index
    @setting_groups = SettingGroup.all
  end

  # GET /setting_groups/1
  # GET /setting_groups/1.json
  def show
  end

  # GET /setting_groups/new
  def new
    @setting_group = SettingGroup.new
  end

  # GET /setting_groups/1/edit
  def edit
  end

  # POST /setting_groups
  # POST /setting_groups.json
  def create
    @setting_group = SettingGroup.new(setting_group_params)

    respond_to do |format|
      if @setting_group.save
        format.html { redirect_to @setting_group, notice: 'Setting group was successfully created.' }
        format.json { render :show, status: :created, location: @setting_group }
      else
        format.html { render :new }
        format.json { render json: @setting_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setting_groups/1
  # PATCH/PUT /setting_groups/1.json
  def update
    respond_to do |format|
      if @setting_group.update(setting_group_params)
        format.html { redirect_to @setting_group, notice: 'Setting group was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting_group }
      else
        format.html { render :edit }
        format.json { render json: @setting_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setting_groups/1
  # DELETE /setting_groups/1.json
  def destroy
    @setting_group.destroy
    respond_to do |format|
      format.html { redirect_to setting_groups_url, notice: 'Setting group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting_group
      @setting_group = SettingGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_group_params
      params.require(:setting_group).permit(:name, :setting_group_id)
    end
end

app/views/setting_groups/_form.html.erb
<%= form_for(@setting_group) do |f| %>
  <% if @setting_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting_group.errors.count, "error") %> prohibited this setting_group from being saved:</h2>

      <ul>
      <% @setting_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :setting_group_id %><br>
    <%= f.text_field :setting_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setting_groups/_setting_group.html.slim
li.setting_group
  h3
    = link_to setting_group.name, edit_setting_group_path(setting_group)
    if-editing
      =< link_to "[x]", setting_group_path(setting_group), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }
  ul.setting_groups
    = render setting_group.setting_groups
  ul.settings
    = render setting_group.settings
    li.setting.new
      = link_to '[+]', new_setting_group_setting_path(setting_group)

app/views/setting_groups/edit.html.slim
h2 Editing Setting Group #{@setting_group.name}

= render 'form'

app/views/setting_groups/index.html.erb
<h2>
  Settings
</h2>

<ul class=setting_groups>
  <%= render @setting_groups %>
</ul>

<if-editing>
  <%= link_to 'New Group', new_setting_group_path %>
</if-editing>

app/views/setting_groups/new.html.erb
<h1>New Setting Group</h1>

<%= render 'form' %>

<%= link_to 'Back', setting_groups_path %>

app/views/setting_groups/show.html.erb
<%= render @setting_group %>

<%= link_to '[e]', edit_setting_group_path(@setting_group) %>