config/routes.rb
Rails.application.routes.draw do
  root to: "users#activity"
  get 'test/new'

  resources :group_users
  patch "/editable", to: "editables#update"
  get "/backend", to: "backend#show", as: 'backend'

  resources :groups
  
  get "/categories/manage", to: "categories#manage", as: 'manage_categories'
  resources :categories, shallow: true do
    get "sub_categories/new", to: "categories#new", as: 'new_sub_category'
    resources :topics, shallow: true do
      resources :posts, shallow: true do
        resources :attachments
      end
    end
  end

  resources :users, shallow: true do
    resources :user_roles
    resources :user_groups
    resources :media
  end
  resources :roles, shallow: true do
    resources :role_permissions
  end
  resources :permissions
    
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :setting_groups, shallow: true do
    resources :settings, shallow: true
  end
  get "/settings", to: "settings#index"
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:group_id, :user_id)
    end
end

app/views/user_groups/_form.html.slim
= form_for @user_group do |f|
  - if @user_group.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user_group.errors.count, "error")} prohibited this user_group from being saved:"
      ul
        - @user_group.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :group
    = f.text_field :group
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/user_groups/edit.html.slim
h1 Editing user_group

== render 'form'

= link_to 'Show', @user_group
'|
= link_to 'Back', user_groups_path

app/views/user_groups/index.html.slim
h1 Listing user_groups

table
  thead
    tr
      th Group
      th User
      th
      th
      th

  tbody
    - @user_groups.each do |user_group|
      tr
        td = user_group.group
        td = user_group.user
        td = link_to 'Show', user_group
        td = link_to 'Edit', edit_user_group_path(user_group)
        td = link_to 'Destroy', user_group, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User group', new_user_group_path

app/views/user_groups/new.html.slim
h1 New user_group

== render 'form'

= link_to 'Back', user_groups_path

app/views/user_groups/show.html.slim
p#notice = notice

p
  strong Group:
  = @user_group.group
p
  strong User:
  = @user_group.user

= link_to 'Edit', edit_user_group_path(@user_group)
'|
= link_to 'Back', user_groups_path