config/routes.rb
Rails.application.routes.draw do
  root to: "users#activity"
  get 'test/new'

  resources :group_users
  patch "/editable", to: "editables#update"
  get "/backend", to: "backend#show", as: 'backend'

  resources :groups
  
  get "/categories/manage", to: "categories#manage", as: 'manage_categories'
  resources :categories, shallow: true do
    get "sub_categories/new", to: "categories#new", as: 'new_sub_category'
    resources :topics, shallow: true do
      resources :posts, shallow: true do
        resources :attachments
      end
    end
  end

  resources :users, shallow: true do
    resources :user_roles
    resources :user_groups
    resources :media
  end
  resources :roles, shallow: true do
    resources :role_permissions
  end
  resources :permissions
    
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :setting_groups, shallow: true do
    resources :settings, shallow: true
  end
  get "/settings", to: "settings#index"
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :setting_group
  @@cache = {}
  
  # read
  def self.[](key)
    return @@cache[key] if @@cache[key]
    if setting = find_by(key: key)
      @@cache[key] = setting.value
      return setting.value
    else
      raise "Setting '#{setting_key}' not found."
    end
  end
  
  # write
  def self.[]=(key, value)
    if setting = find_by_key(key)
      setting.update(value: value)
    else
      raise "Setting '#{setting_key}' not found."
    end    
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @setting_groups = SettingGroup.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting_group = SettingGroup.find(params[:setting_group_id])
    @setting = @setting_group.settings.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:key, :value, :type, :name, :description, :setting_group_id, :order)
    end
end

app/views/settings/_form.html.erb
<%= form_for([@setting_group, @setting]) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="field">
    <%= f.label :datatype %><br>
    <%= f.text_field :datatype %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :setting_group_id %><br>
    <%= f.text_field :setting_group_id %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.slim
li.setting
  .name title=setting.key
    = link_to setting.name, edit_setting_path(setting)
  .value
    = setting.value
  .description
    = setting.description
  .delete.if-editing
    = link_to "[x]", setting_path(setting), method: :delete, data: { confirm: 'sure?' }

app/views/settings/edit.html.erb
<h2>Editing Setting</h2>

<%= render 'form' %>

<%= link_to 'Show', @setting %>

app/views/settings/index.html.slim
h2
  Settings

ul.setting_groups
  = render @setting_groups

if-editing
  = link_to 'New Group', new_setting_group_path

app/views/settings/new.html.erb
<h2>New Setting</h2>

<%= render 'form' %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<p>
  <strong>Type:</strong>
  <%= @setting.datatype %>
</p>

<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @setting.description %>
</p>

<p>
  <strong>Setting group:</strong>
  <%= @setting.setting_group %>
</p>

<p>
  <strong>Order:</strong>
  <%= @setting.order %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>