config/routes.rb
Rails.application.routes.draw do
  root to: "users#activity"
  get 'test/new'

  resources :group_users
  patch "/editable", to: "editables#update"
  get "/backend", to: "backend#show", as: 'backend'

  resources :groups
  
  get "/categories/manage", to: "categories#manage", as: 'manage_categories'
  resources :categories, shallow: true do
    get "sub_categories/new", to: "categories#new", as: 'new_sub_category'
    resources :topics, shallow: true do
      resources :posts, shallow: true do
        resources :attachments
      end
    end
  end

  resources :users, shallow: true do
    resources :user_roles
    resources :user_groups
    resources :media
  end
  resources :roles, shallow: true do
    resources :role_permissions
  end
  resources :permissions
    
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :setting_groups, shallow: true do
    resources :settings, shallow: true
  end
  get "/settings", to: "settings#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories, foreign_key: 'parent_id'
  has_many :topics
  belongs_to :category

  scope :root, ->{ where("parent_id IS NULL") }


  def self.visible_for user
    where("id IN(?)", AccessControl.category_ids_visibile_for(user))
  end

  def parent_categories
    unless @parent_categories
      @parent_categories = []
      collect_parent_categories self
    end
    @parent_categories
  end

  def collect_parent_categories category
    if category.category
      @parent_categories << category.category
      collect_parent_categories category.category
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout "backend", only: [:manage]
  
  def manage
    @categories = Category.root
  end
  
  # GET /categories
  # GET /categories.json
  def index
#    @categories = Category.root.visible_for current_user
    @categories = current_user.categories.root
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    authorize read: @category
  end

  # GET /categories/new
  def new
    if params[:category_id]
      @category = Category.find(params[:category_id]).categories.new
    else
      @category = Category.new
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/views/categories/_category.html.erb
<forum-category>
  <h2><%= link_to category.name, category %></h2>
  <ul>
    <%= render collection: category.categories, as: :category, partial: "sub_category" %>
  </ul>
</forum-category>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.collection_select(:parent_id, Category.where.not(id: @category.id), :id, :name, prompt: true, include_blank: "Root") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_manage_category.html.slim
li
  = editable category, :name, trigger: :auto
  =< link_to '[+]', category_new_sub_category_path(category)
  =< link_to '[x]', category, data: {:confirm => 'Are you sure?'}, :method => :delete
  - if category.categories.any?
    ul
      = render collection: category.categories, as: :category, partial: "manage_category"
        

app/views/categories/_sub_category.html.erb
<li class=sub-category>
  <h3><%= link_to category.name, category %></h3>
</li>

app/views/categories/edit.html.erb
<h2>Editing Category</h2>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.slim
= render @categories

app/views/categories/manage.html.slim
h2
  | manage categories
  =< link_to '[+]', new_category_path

ul
  = render collection: @categories, as: :category, partial: "manage_category"

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.slim
h2
  = editable @category, :name, trigger: :button

= editable @category, :description, trigger: :button

<!-- sub categories -->
ul
  = render partial: "sub_category", collection: @category.categories, as: :category

<!-- topics -->
ul.topics
  = render @category.topics
  li
    = link_to 'New Topic', new_category_topic_path(@category)